### ISSUE TITLE
BioActivity for human targets

### ISSUE THREAD

**Issue by chung88** [schurerlab/scuba#1]
SELECT component_type, tid, description, accession, organism
FROM public.target_components tc
INNER JOIN public.component_sequences cs
ON tc.component_id = cs.component_id
WHERE tid = 8
  

organism = 'Homo sapiens'

**Comment by chung88** [comment]
SELECT tc.tid, td.target_type, cs.component_type, td.organism, count(*)
FROM public.target_components tc
    INNER JOIN public.component_sequences cs
        ON tc.component_id = cs.component_id
    INNER JOIN public.target_dictionary td
        ON td.tid = tc.tid
    WHERE td.organism = 'Homo sapiens'
    AND td.target_type = 'SINGLE PROTEIN'
    GROUP BY tc.tid, td.target_type, cs.component_type, td.organism
GO

**Comment by whinis** [comment]
select count(tid),tid from (SELECT distinct tc.tid, td.organism
FROM public.target_components tc
INNER JOIN public.component_sequences cs
ON tc.component_id = cs.component_id 
INNER JOIN public.target_dictionary td
ON td.tid = tc.tid
WHERE td.organism = 'Homo sapiens'
AND td.target_type = 'SINGLE PROTEIN'
) as t
group by t.tid
having count(tid) > 1
order by count(tid) desc


Shows no counts having more than 1

**Comment by chung88** [comment]
@whinis @chung88 confirmed 
Single protein has 1 (tid) to 1 (accession)
